#!/usr/bin/env bash
#
# Print the paths of the package files that would be created by building the
# given PKGBUILD.

set -e

# Assume $1 is the prefix, and $2 is the package name.
prefix="$1"
_name="$2"

safe_source() {
    if ! . "$@"; then
        echo "Failed to source '$@'!"
        exit 1
    fi
}

# Change to that directory.
pushd "${rootdir}/${prefix}/${_name}" > /dev/null

conf="$(mktemp "${TMPDIR:-/tmp}/${prefix}-makepkg-conf.XXXX")" || \
    error "$?" "Failed to generate a makepkg.conf!"
trap "rm -f '${conf}'" EXIT
cat /etc/makepkg.conf ../../config.sh ../makepkg.conf > "${conf}"
safe_source "${conf}" # Source the config.

# Print the names and paths. Ignore any non-relevant architectures.
for name in $(makepkg --packagelist --config "${conf}" | \
    grep -e '-any$' -e "-${CARCH}$"); do
    printf "%s\n" "${rootdir}/${prefix}/${_name}/${name}${PKGEXT}"
done

# Head back up again.
popd > /dev/null
