#!/usr/bin/env bash
#
# Print the paths of the package files that would be created by building the
# given PKGBUILD.

set -e

# Assume $1 is the prefix, and $2 is the package name.
prefix="$1"
_name="$2"

safe_source() {
    if ! . "$@"; then
        echo "Failed to source '$@'!"
        exit 1
    fi
}

safe_source "${rootdir}/${prefix}/makepkg.conf" # Source the config.
safe_source "${rootdir}/${prefix}/${_name}/PKGBUILD" # Source the actual package.

# Generate the names...
for name in "${pkgname[@]}"; do

    if [ "${arch}" == "any" ]; then
        actual_arch="any"
    else
        actual_arch="${CARCH}"
    fi

    echo "${rootdir}/${prefix}/${_name}/${name}-${pkgver}-${pkgrel}-${actual_arch}${PKGEXT}"
done

